# Generated by Django 5.0 on 2024-10-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertocompetitionrelationship',
            old_name='Competition',
            new_name='competition',
        ),
        migrations.RenameField(
            model_name='usertocompetitionrelationship',
            old_name='User',
            new_name='user',
        ),
    ]
