# Generated by Django 5.0 on 2024-10-17 13:27

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_competition_usertocompetitionrelationship_competition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertocompetitionrelationship',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='usertocompetitionrelationship',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='usertocompetitionrelationship',
            name='competition',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_relationships', to='api.competition'),
        ),
    ]
