# Generated by Django 5.0 on 2024-10-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usertocompetitionrelationship_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='participants',
        ),
    ]
