# Generated by Django 5.0 on 2024-03-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_competition_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
