# Generated by Django 5.0 on 2024-04-12 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_competition_max_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToCompetitionRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField()),
                ('status', models.TextField(blank=True, null=True)),
                ('Competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.competition')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='participants'
        ),
        migrations.AddField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(related_name='competitions', through='api.UserToCompetitionRelationship',
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
