# Generated by Django 5.0 on 2024-04-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usertocompetitionrelationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertocompetitionrelationship',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
