# Generated by Django 5.0 on 2024-10-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_round_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='name',
            field=models.CharField(choices=[('Q', 'Qualification'), ('E', '1/8 Finals'), ('F', 'Quarterfinals'), ('S', 'Semifinals'), ('T', 'Finals')], default='Q', max_length=20),
        ),
        migrations.AlterField(
            model_name='usertocompetitionrelationship',
            name='status',
            field=models.CharField(choices=[('P', 'Pending Request'), ('R', 'Request Accepted'), ('N', 'Not Qualified'), ('Q', 'Qualified'), ('E', '1/8 Finalist'), ('F', '1/4 Finalist'), ('S', 'Semifinalist'), ('V', 'Finals'), ('T', '2nd Place'), ('W', 'Won')], default='P', max_length=1),
        ),
    ]
