# Generated by Django 5.0 on 2024-10-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_round_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='number',
        ),
    ]
