# Generated by Django 5.0 on 2024-05-03 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_degree_of_studies_user_email_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverificationtoken',
            old_name='Token',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='forgotpasswordtoken',
            old_name='Token',
            new_name='token',
        ),
    ]
