# Generated by Django 5.0 on 2024-10-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_match_player1_alter_match_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
