# Generated by Django 5.0 on 2024-10-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_round_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integral',
            name='Series',
        ),
        migrations.RemoveField(
            model_name='integral',
            name='solution',
        ),
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.AlterField(
            model_name='match',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertocompetitionrelationship',
            name='status',
            field=models.CharField(choices=[('P', 'Pending Request'), ('R', 'Request Accepted'), ('N', 'Not Qualified'), ('Q', 'Qualified'), ('E', '1/8 Finalist'), ('F', '1/4 Finalist'), ('S', 'Semifinalist'), ('V', 'Finalist'), ('T', '2nd Place'), ('W', 'Won')], default='P', max_length=1),
        ),
        migrations.DeleteModel(
            name='IntegralsSeries',
        ),
        migrations.DeleteModel(
            name='Integral',
        ),
        migrations.DeleteModel(
            name='IntegralSolution',
        ),
    ]
