# Generated by Django 5.0 on 2024-05-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Moderator'), (3, 'Editor'), (4, 'User')], default=4),
        ),
    ]
