# Generated by Django 5.0 on 2024-10-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_integral_series_remove_integral_solution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='match_winner',
            field=models.CharField(blank=True, choices=[('player1', 'Player 1'), ('player2', 'Player 2')], max_length=7, null=True),
        ),
    ]
