# Generated by Django 5.0 on 2024-10-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_match_winner_match_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
