# Generated by Django 5.0 on 2024-05-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_integralsolution_integralsseries_integral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integral',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='integralsolution',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='integralsseries',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
