# Generated by Django 5.0 on 2024-10-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_competition_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='propagate_winner',
            field=models.BooleanField(default=True),
        ),
    ]
