# Generated by Django 5.1.2 on 2024-10-30 23:49

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_competition_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='series',
            field=wagtail.fields.StreamField([('series', 5)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('finals', 'Finals'), ('semifinals', 'Semifinals'), ('quarterfinals', 'Quarterfinals'), ('eighth-finals', 'Eighth-finals'), ('16th-finals', '16th-finals'), ('32nd-finals', '32nd-finals'), ('64th-finals', '64th-finals'), ('preliminary', 'Preliminary'), ('practice', 'Practice'), ('spare', 'Spare'), ('other', 'Other')], 'help_text': 'Select the series', 'required': False}), 1: ('wagtailmath.blocks.MathBlock', (), {'required': False}), 2: ('wagtail.blocks.IntegerBlock', (), {'default': 5, 'help_text': 'Difficulty level (1-10)', 'max_value': 10, 'min_value': 1}), 3: ('wagtail.blocks.StructBlock', [[('integral', 1), ('integral_solution', 1), ('difficulty_level', 2)]], {}), 4: ('wagtail.blocks.StreamBlock', [[('integral', 3)]], {'help_text': 'Integrals belonging to this series', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('series_name', 0), ('integrals', 4)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='usertocompetitionrelationship',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending Request'), ('R', 'Request Accepted'), ('N', 'Not Qualified'), ('Q', 'Qualified'), ('E', '1/8 Finalist'), ('F', '1/4 Finalist'), ('S', 'Semifinalist'), ('V', 'Finalist'), ('T', '2nd Place'), ('W', 'Won')], default='P', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='usertocompetitionrelationship',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
