# Generated by Django 5.1.2 on 2024-10-31 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_competition_name_alter_competition_series_and_more'),
        ('api', '0019_alter_competition_series'),
    ]

    operations = [
    ]
