# Generated by Django 5.1.2 on 2024-10-31 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_20241031_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='close_registration',
            field=models.CharField(blank=True, default='Registration Closed', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertocompetitionrelationship',
            name='status',
            field=models.CharField(choices=[('P', 'Pending Request'), ('R', 'Request Accepted'), ('N', 'Not Qualified'), ('Q', 'Qualified'), ('E', '1/8 Finalist'), ('F', '1/4 Finalist'), ('S', 'Semifinalist'), ('V', 'Finalist'), ('T', '2nd Place'), ('W', 'Won')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='usertocompetitionrelationship',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
