# Generated by Django 5.1.2 on 2024-10-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_competition_close_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
