# Generated by Django 5.1.2 on 2024-10-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_competition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='max_participants',
            field=models.IntegerField(null=True),
        ),
    ]
