# Generated by Django 5.1.2 on 2024-10-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_usertocompetitionrelationship_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name_pronunciation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='usertocompetitionrelationship',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='usertocompetitionrelationship',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertocompetitionrelationship',
            name='emergency_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usertocompetitionrelationship',
            name='name_pronunciation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertocompetitionrelationship',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usertocompetitionrelationship',
            name='program_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
