# Generated by Django 5.1.2 on 2024-10-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_user_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertocompetitionrelationship',
            name='name_pronunciation',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
