# Generated by Django 5.1.2 on 2024-11-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_usertocompetitionrelationship_show_in_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='show_in_admin',
        ),
        migrations.AddField(
            model_name='competition',
            name='participants_filter',
            field=models.CharField(choices=[('PENDING_REQUEST', 'Pending Request'), ('REQUEST_ACCEPTED', 'Request Accepted'), ('IN_COMPETITION', 'In Competition'), ('ALL', 'All')], default='ALL', max_length=20),
        ),
    ]
