# Generated by Django 5.1.2 on 2024-11-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_usertocompetitionrelationship_name_pronunciation'),
        ('api', '0030_remove_competition_show_in_admin_and_more'),
    ]

    operations = [
    ]
