# Generated by Django 5.1.2 on 2024-11-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_usertocompetitionrelationship_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='participants_filter',
            field=models.CharField(blank=True, choices=[('PENDING_REQUEST', 'Pending Request'), ('REQUEST_ACCEPTED', 'Request Accepted'), ('IN_COMPETITION', 'In Competition'), ('ALL', 'All')], default='ALL', max_length=20),
        ),
    ]
