# Generated by Django 5.1.2 on 2024-11-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_competition_participants_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='event_date',
            new_name='event_date_end',
        ),
        migrations.AddField(
            model_name='competition',
            name='event_date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
