# Generated by Django 5.1.2 on 2024-11-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_usertocompetitionrelationship_name_pronunciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertocompetitionrelationship',
            name='name_pronunciation',
            field=models.TextField(blank=True, max_length=2, null=True),
        ),
    ]
