# Generated by Django 5.1.2 on 2025-01-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_competition_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ranking_elo',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, default='Austria', max_length=100, null=True),
        ),
    ]
