# Generated by Django 5.1.2 on 2025-01-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_user_ranking_elo_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ranking_elo_gym',
            field=models.IntegerField(default=1000),
        ),
    ]
