# Generated by Django 5.1.2 on 2025-01-28 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_user_ranking_elo_alter_user_ranking_elo_gym'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIntegral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_author', models.CharField(blank=True, help_text='Add author', max_length=255, null=True)),
                ('difficulty_level', models.IntegerField(blank=True, default=5, help_text='Difficulty level (1-10)', null=True)),
                ('date', models.DateField(blank=True, help_text='Which date this integral is for', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='gym_daily_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='gym_daily_streak_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='gym_last_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyIntegralToUserRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('integral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dailyintegral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'integral')},
            },
        ),
    ]
