# Generated by Django 5.1.2 on 2025-01-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_dailyintegral_user_gym_daily_streak_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyintegral',
            options={'ordering': ['-date'], 'verbose_name': 'Daily Integral', 'verbose_name_plural': 'Daily Integrals'},
        ),
    ]
