# Generated by Django 5.1.2 on 2025-01-28 15:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_dailyintegral_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyintegral',
            name='integral',
            field=wagtail.fields.StreamField([('integral', 0), ('integral_answer', 0)], blank=True, block_lookup={0: ('wagtailmath.blocks.MathBlock', (), {'required': True})}, null=True),
        ),
    ]
