# Generated by Django 5.1.2 on 2025-01-28 15:15

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_dailyintegral_integral'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyintegral',
            name='integral_answer',
            field=models.CharField(blank=True, help_text='Add answer', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailyintegral',
            name='integral',
            field=wagtail.fields.StreamField([('integral', 0)], blank=True, block_lookup={0: ('wagtailmath.blocks.MathBlock', (), {'required': True})}, null=True),
        ),
    ]
