# Generated by Django 5.1.2 on 2025-01-28 15:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_dailyintegral_integral_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyintegral',
            name='integral',
            field=wagtail.fields.StreamField([('integral', 0)], blank=True, block_lookup={0: ('wagtailmath.blocks.MathBlock', (), {'required': True})}, default=[('integral', '\\int_{0}^{1} x^2 \\, dx')], null=True),
        ),
    ]
