# Generated by Django 5.1.2 on 2025-01-28 16:09

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_dailyintegral_latest_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyintegraltouserrelationship',
            name='integral',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relationships', to='api.dailyintegral'),
        ),
    ]
