# Generated by Django 5.1.2 on 2025-06-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_dailyintegraltouserrelationship_integral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ranking_elo_gym',
        ),
        migrations.AddField(
            model_name='user',
            name='ranking_gym',
            field=models.IntegerField(default=0),
        ),
    ]
