# Generated by Django 5.1.2 on 2025-06-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_remove_user_ranking_elo_gym_user_ranking_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='decay_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='ranking_elo',
            field=models.FloatField(default=580),
        ),
    ]
