# Generated by Django 5.1.2 on 2025-06-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_competition_decay_applied_alter_user_ranking_elo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, default='No Affiliation', max_length=100, null=True),
        ),
    ]
