# Generated by Django 5.0 on 2024-10-16 21:14

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('about_us', models.TextField(null=True)),
                ('contacts', models.TextField(null=True)),
                ('socials', models.TextField(blank=True, null=True)),
                ('our_team', wagtail.fields.StreamField([('team_member', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='add name', required=True)), ('role', wagtail.blocks.CharBlock(help_text='add role', required=True)), ('contacts', wagtail.blocks.TextBlock(help_text='add contacts', required=True)), ('picture', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CompetitionPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header', models.CharField(max_length=100)),
                ('short_description', wagtail.fields.RichTextField(null=True)),
                ('description', wagtail.fields.RichTextField(null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('place', models.CharField(max_length=100)),
                ('place_maps_url', models.CharField(blank=True, max_length=100, null=True)),
                ('rules', wagtail.fields.RichTextField(null=True)),
                ('related_competition_id', models.IntegerField(blank=True, null=True)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('related_competition_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.competition', verbose_name='api_competition')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_section_header', models.CharField(max_length=50, null=True)),
                ('title_section_description', wagtail.fields.RichTextField(null=True)),
                ('bullet_points_section_header', models.CharField(max_length=50, null=True)),
                ('bullet_points', wagtail.fields.StreamField([('home_bullet_point', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(help_text='add header', required=True)), ('text', wagtail.blocks.TextBlock(help_text='add text', required=True))]))], blank=True, null=True, use_json_field=True)),
                ('project_description', wagtail.fields.RichTextField(null=True)),
                ('youtube_video_link', models.CharField(blank=True, max_length=150, null=True)),
                ('main_sponsor_description', wagtail.fields.RichTextField(null=True)),
                ('sponsors', wagtail.fields.StreamField([('sponsor', wagtail.blocks.StructBlock([('sponsor_picture', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True, use_json_field=True)),
                ('acknowledgements', wagtail.fields.StreamField([('thanks_to', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='add name', required=True))]))], blank=True, null=True, use_json_field=True)),
                ('homepage_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('main_sponsor_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header', models.CharField(max_length=100)),
                ('text', wagtail.fields.RichTextField(null=True)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
