# Generated by Django 5.0 on 2024-10-17 11:20

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_competitionpost_related_competition_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='main_sponsor_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='main_sponsor_picture',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sponsors',
            field=wagtail.fields.StreamField([('sponsor', wagtail.blocks.StructBlock([('sponsor_name', wagtail.blocks.CharBlock(max_length=100, required=True)), ('sponsor_logo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('sponsor_tier', wagtail.blocks.ChoiceBlock(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('partner', 'Partner'), ('supporter', 'Supporter')])), ('sponsor_description', wagtail.blocks.RichTextBlock(features=['bold', 'link'], required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
