# Generated by Django 5.0 on 2024-03-27 11:44

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_homepage_picture'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('about_us', models.TextField(null=True)),
                ('contacts', models.TextField(null=True)),
                ('socials', models.TextField(blank=True, null=True)),
                ('our_team', wagtail.fields.StreamField([('team_member', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='add name', required=True)), ('role', wagtail.blocks.CharBlock(help_text='add role', required=True)), ('contacts', wagtail.blocks.TextBlock(help_text='add contacts', required=True)), ('picture', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
