# Generated by Django 5.0 on 2024-02-17 20:08

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_welcome_header_homepage_bullet_points_section_header_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='bullet_points_bullet_point_1',
        ),
        migrations.AddField(
            model_name='homepage',
            name='bullet_points',
            field=wagtail.fields.StreamField([('home_bullet_point', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(help_text='add header', required=True)), ('text', wagtail.blocks.TextBlock(help_text='add header', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
