# Generated by Django 5.0 on 2024-03-30 17:06

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sponsors',
            field=wagtail.fields.StreamField([('sponsor_picture', wagtail.blocks.StructBlock([('sponsor_picture', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True, use_json_field=True),
        ),
    ]
