# Generated by Django 5.0 on 2024-02-18 15:13

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_bullet_points_bullet_point_1_and_more'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='bullet_points',
            field=wagtail.fields.StreamField([('home_bullet_point', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(help_text='add header', required=True)), ('text', wagtail.blocks.TextBlock(help_text='add text', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
