# Generated by Django 5.0 on 2024-10-17 11:54

import wagtail.blocks
import wagtail.fields
import wagtailmath.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_imprintpage_termsofusepage_competitionpost_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionpost',
            name='series',
            field=wagtail.fields.StreamField([('series', wagtail.blocks.StructBlock([('series_name', wagtail.blocks.ChoiceBlock(choices=[('semifinal', 'Semifinal'), ('quarter_final', 'Quarter Final'), ('blitz', 'Blitz'), ('spare', 'Spare Integrals')], help_text='Select the series')), ('integrals', wagtail.blocks.StreamBlock([('integral', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='Simple reference name', max_length=255, required=True)), ('latex_code', wagtailmath.blocks.MathBlock(help_text='LaTeX code for the integral', required=True)), ('solution', wagtailmath.blocks.MathBlock(help_text='Full solution in LaTeX format', required=True)), ('answer', wagtail.blocks.CharBlock(help_text='The final answer', max_length=255, required=True)), ('difficulty_level', wagtail.blocks.IntegerBlock(default=1, help_text='Difficulty level (1-10)', max_value=10, min_value=1)), ('position', wagtail.blocks.IntegerBlock(help_text='Position within the series', required=True))]))], help_text='Integrals belonging to this series', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
