# Generated by Django 5.0 on 2024-03-30 17:12

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='Acknowledgements',
            field=wagtail.fields.StreamField([('thanks_to', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='add header', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sponsors',
            field=wagtail.fields.StreamField([('sponsor', wagtail.blocks.StructBlock([('sponsor_picture', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True, use_json_field=True),
        ),
    ]
