# Generated by Django 5.0 on 2024-02-25 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_newspage_alter_homepage_bullet_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('homepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.homepage')),
                ('page_title', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('home.homepage',),
        ),
    ]
