# Generated by Django 5.0 on 2024-03-30 17:21

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_acknowledgements_alter_homepage_sponsors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='Acknowledgements',
        ),
        migrations.AddField(
            model_name='homepage',
            name='acknowledgements',
            field=wagtail.fields.StreamField([('thanks_to', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='add name', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
