# Generated by Django 5.0 on 2024-02-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_indexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexPage',
        ),
    ]
