# Generated by Django 5.0 on 2024-04-12 21:10

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_competition_max_participants'),
        ('home', '0007_remove_homepage_acknowledgements_and_more'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='content',
        ),
        migrations.AddField(
            model_name='competition',
            name='related_competition_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.competition', verbose_name='api_competition'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='example_youtube_video_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_sponsor_description',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_sponsor_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='project_description',
            field=wagtail.fields.RichTextField(null=True),
        ),
    ]
