# Generated by Django 5.0 on 2024-10-17 13:11

import wagtail.blocks
import wagtail.fields
import wagtailmath.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_competitionpost_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionpost',
            name='series',
            field=wagtail.fields.StreamField([('series', wagtail.blocks.StructBlock([('series_name', wagtail.blocks.ChoiceBlock(choices=[('finals', 'Finals'), ('semifinals', 'Semifinals'), ('quarterfinals', 'Quarterfinals'), ('eighth-finals', 'Eighth-finals'), ('16th-finals', '16th-finals'), ('32nd-finals', '32nd-finals'), ('64th-finals', '64th-finals'), ('preliminary', 'Preliminary'), ('practice', 'Practice'), ('spare', 'Spare'), ('other', 'Other')], help_text='Select the series')), ('integrals', wagtail.blocks.StreamBlock([('integral', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='Simple reference name', max_length=255, required=True)), ('latex_code', wagtailmath.blocks.MathBlock(help_text='LaTeX code for the integral', id='integral', required=True)), ('solution_steps', wagtail.blocks.StreamBlock([('solution_step', wagtail.blocks.StructBlock([('latex_code', wagtailmath.blocks.MathBlock(help_text='LaTeX code for the step', id='step', required=True))]))], help_text='Steps to solve the integral', required=True)), ('answer', wagtail.blocks.CharBlock(help_text='The final answer', max_length=255, required=True)), ('difficulty_level', wagtail.blocks.IntegerBlock(default=1, help_text='Difficulty level (1-10)', max_value=10, min_value=1))]))], help_text='Integrals belonging to this series', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
