# Generated by Django 5.0 on 2024-10-18 11:43

import wagtail.blocks
import wagtail.fields
import wagtailmath.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_competitionpost_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionpost',
            name='series',
            field=wagtail.fields.StreamField([('series', wagtail.blocks.StructBlock([('series_name', wagtail.blocks.ChoiceBlock(choices=[('finals', 'Finals'), ('semifinals', 'Semifinals'), ('quarterfinals', 'Quarterfinals'), ('eighth-finals', 'Eighth-finals'), ('16th-finals', '16th-finals'), ('32nd-finals', '32nd-finals'), ('64th-finals', '64th-finals'), ('preliminary', 'Preliminary'), ('practice', 'Practice'), ('spare', 'Spare'), ('other', 'Other')], help_text='Select the series')), ('integrals', wagtail.blocks.StreamBlock([('integral', wagtail.blocks.StructBlock([('integral', wagtailmath.blocks.MathBlock(required=True)), ('integral_solution', wagtailmath.blocks.MathBlock(required=False)), ('difficulty_level', wagtail.blocks.IntegerBlock(default=5, help_text='Difficulty level (1-10)', max_value=10, min_value=1))]))], help_text='Integrals belonging to this series', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
