# Generated by Django 5.0 on 2024-10-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_competitionpost_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionpost',
            name='series',
        ),
    ]
