# Generated by Django 5.0 on 2024-10-28 12:09

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_match_winner_match_match_winner'),
        ('home', '0014_remove_competitionpost_series'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='acknowledgements',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='bullet_points',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='bullet_points_section_header',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='homepage_picture',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_section_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_section_header',
        ),
        migrations.AddField(
            model_name='homepage',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.competition', verbose_name='competition'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slogan',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_media_links',
            field=wagtail.fields.StreamField([('social_media_link', wagtail.blocks.StructBlock([('social_media_name', wagtail.blocks.CharBlock(max_length=100, required=True)), ('social_media_link', wagtail.blocks.URLBlock(max_length=100, required=True))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='steps_to_participate',
            field=wagtail.fields.StreamField([('step_to_participate', wagtail.blocks.StructBlock([('step_number', wagtail.blocks.IntegerBlock(max_value=3, min_value=1, required=True)), ('step_title', wagtail.blocks.CharBlock(max_length=100, required=True)), ('step_description', wagtail.blocks.CharBlock(max_length=500, required=True))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Title Background Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='what_is_it_content',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_participate_content',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_participate_header',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
