# Generated by Django 5.0 on 2024-10-28 17:42

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_homepage_acknowledgements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='why_participate_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='why_participate_header',
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_participate',
            field=wagtail.fields.StreamField([('reason', wagtail.blocks.StructBlock([('reason_number', wagtail.blocks.IntegerBlock(min_value=1, required=True)), ('header', wagtail.blocks.CharBlock(max_length=100, required=True)), ('content', wagtail.blocks.CharBlock(max_length=500, required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
