# Generated by Django 5.0 on 2024-10-28 19:06

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_homepage_sponsors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='sponsors',
            field=wagtail.fields.StreamField([('sponsor', wagtail.blocks.StructBlock([('sponsor_name', wagtail.blocks.CharBlock(max_length=100, required=True)), ('sponsor_logo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('sponsor_logo_size', wagtail.blocks.CharBlock(max_length=3, required=True)), ('sponsor_tier', wagtail.blocks.ChoiceBlock(choices=[('main', 'Main'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('partner', 'Partner'), ('supporter', 'Supporter')])), ('sponsor_description', wagtail.blocks.RichTextBlock(features=['bold', 'link'], required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
