# Generated by Django 5.0 on 2024-10-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_homepage_slogan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionpost',
            name='event_date',
        ),
    ]
