# Generated by Django 5.0 on 2024-10-29 21:18

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_privacypolicypage_remove_newspost_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionpost',
            name='sections',
            field=wagtail.fields.StreamField([('section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title of the section', max_length=50, required=True)), ('body', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Text of the section', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
