# Generated by Django 5.0 on 2024-10-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_competitionpost_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionpost',
            name='place_maps_url',
        ),
        migrations.AddField(
            model_name='competitionpost',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
