# Generated by Django 5.1.2 on 2024-10-30 23:33

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_competitionpost_place_maps_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactspage',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='socials',
        ),
        migrations.AddField(
            model_name='contactspage',
            name='inquiry_email',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='about_us',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='our_team',
            field=wagtail.fields.StreamField([('team_member', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'add name', 'max_length': 25, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'add role', 'max_length': 25, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'add phone', 'max_length': 25, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'add email', 'max_length': 25, 'required': True}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 1), ('phone', 2), ('email', 3), ('picture', 4)]], {})}, null=True),
        ),
    ]
