# Generated by Django 5.1.2 on 2024-10-30 23:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_contactspage_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionpost',
            name='sections',
            field=wagtail.fields.StreamField([('section', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title of the section', 'max_length': 50, 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Text of the section', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 1)]], {})}, null=True),
        ),
    ]
