# Generated by Django 5.1.2 on 2024-10-31 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_competitionpost_sections'),
        ('home', '0027_alter_competitionpost_sections_and_more'),
    ]

    operations = [
    ]
