# Generated by Django 5.1.2 on 2024-10-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_merge_20241031_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactspage',
            name='inquiry_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
