# Generated by Django 5.1.2 on 2024-10-31 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_user_additional_info_and_more'),
        ('home', '0033_alter_competitionpost_picture'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionpost',
            name='competition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_page', to='api.competition', verbose_name='competition'),
        ),
        migrations.AlterField(
            model_name='competitionpost',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image'),
        ),
    ]
