# Generated by Django 5.1.2 on 2024-11-01 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_event_date_competition_event_date_end_and_more'),
        ('home', '0034_alter_competitionpost_competition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.competition', verbose_name='competition'),
        ),
    ]
