# Generated by Django 5.1.2 on 2024-11-07 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_homepage_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.competitionpost', verbose_name='competitionpost'),
        ),
    ]
