# Generated by Django 5.1.2 on 2024-11-15 00:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_homepage_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionpost',
            name='rules',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
