# Generated by Django 5.0 on 2024-02-17 20:04

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_welcome_description_homepage_welcome_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='welcome_Header',
            new_name='bullet_points_section_header',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='welcome_Description',
            new_name='title_section_description',
        ),
        migrations.AddField(
            model_name='homepage',
            name='bullet_points_bullet_point_1',
            field=wagtail.fields.StreamField([('home_bullet_point_1', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(help_text='add header', required=True)), ('text', wagtail.blocks.TextBlock(help_text='add header', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_section_header',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
