# Generated by Django 5.0 on 2024-02-25 16:50

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_newspage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='content',
            field=wagtail.fields.StreamField([('news', wagtail.blocks.StructBlock([]))], blank=True, null=True, use_json_field=True),
        ),
    ]
